language: objective-c
# osx_image: xcode9
osx_image: xcode9

# env:
#   global:
#     - LC_CTYPE=en_US.UTF-8
#     - LANG=en_US.UTF-8

# before_install:
#     - env
#     - locale
#     - xcpretty --version
#     - xcodebuild -version
#     - xcodebuild -showsdks

# script:
#     - set -o pipefail
#     - xcodebuild -project TransitionViewControllerDemo.xcodeproj -scheme TransitionViewControllerDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#     # - xcodebuild -configuration Debug -project TransitionViewControllerDemo.xcodeproj -scheme TransitionViewControllerDemo -sdk iphonesimulator clean build

# xcode_project: TransitionViewControllerDemo.xcodeproj # path to your xcodeproj folder
# xcode_scheme: TransitionViewControllerDemoTests
# script:
#   - uname -a
#   - xcodebuild -workspace TransitionViewControllerDemo.xcodeproj -scheme TransitionViewControllerDemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3' build test | xcpretty -c


# # references:
# # * http://www.objc.io/issue-6/travis-ci.html
# # * https://github.com/supermarin/xcpretty#usage

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
  - xcodebuild clean build -workspace Example/TransitionViewController.xcworkspace -scheme 'TransitionViewController-Example' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty
  # - set -o pipefail && xcodebuild test -workspace Example/TransitionViewController.xcworkspace -scheme 'TransitionViewController-Example' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3' -configuration Debug -enableCodeCoverage YES | xcpretty
  - xcodebuild test -workspace Example/TransitionViewController.xcworkspace -scheme 'TransitionViewController-Example' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3' -configuration Debug -enableCodeCoverage YES | xcpretty
  - pod lib lint TransitionViewController.podspec

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 8a5d0a53-2663-44df-8b8a-44d4e2a36ba7