language: objective-c
osx_image: xcode9

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - xcodebuild -project TransitionViewControllerDemo.xcodeproj -scheme TransitionViewControllerDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    # - xcodebuild -configuration Debug -project TransitionViewControllerDemo.xcodeproj -scheme TransitionViewControllerDemo -sdk iphonesimulator clean build

# xcode_project: TransitionViewControllerDemo.xcodeproj # path to your xcodeproj folder
# xcode_scheme: TransitionViewControllerDemoTests
# script:
#   - uname -a
#   - xcodebuild -workspace TransitionViewControllerDemo.xcodeproj -scheme TransitionViewControllerDemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3' build test | xcpretty -c