language: objective-c
osx_image: xcode9

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - xcodebuild clean build -workspace Example/TransitionViewController.xcworkspace -scheme 'TransitionViewController-Example' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty
    - xcodebuild test -workspace Example/TransitionViewController.xcworkspace -scheme 'TransitionViewController-Example' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3' -configuration Debug -enableCodeCoverage YES | xcpretty
    - pod lib lint TransitionViewController.podspec